image: python:latest

stages:
  - build
  - test
  - deploy

cache:
  paths:
    - .oi/
    - .pio/
    - docs/build/

build:firmware:
  stage: build
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
  before_script:
    - pip install -U platformio
    - pio platform update
  script:
    - pio run -t clean
    - pio run -e core
    # - pio run -e discrete
    # - pio run -e discreteve
    # - pio run -e stepper
    # - pio run -e stepperve
    # - pio run -e mixed
    # - pio run -e relayhp
    # - pio run -e relaylp
  rules:
    - if: '($CI_PIPELINE_SOURCE == "merge_request_event") && ($CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "master" || "dev")'

build:examples:
  stage: build
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
  script: echo "build examples"
  rules:
    - if: '($CI_PIPELINE_SOURCE == "merge_request_event") && ($CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "master" || "dev")'

build:docs:
  stage: build
  before_script:
    - pip install virtualenv
    - export PATH="$HOME/.local/bin:$PATH"
    - virtualenv venv
    - source venv/bin/activate
    - pip install -r docs/requirements.txt
  script:
    - cd docs
    - make clean
    - doxygen doxygen/Doxyfile
    - make html
  rules:
    - if: '($CI_PIPELINE_SOURCE == "merge_request_event") && ($CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "master" || "dev")'

test:firmware:
  stage: test
  needs:
    - job: build:firmware
  script: 
    - echo "pio run -t upload"
    - echo "pio test"
  rules:
    - if: '($CI_PIPELINE_SOURCE == "merge_request_event") && ($CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "master" || "dev")'

deploy:bin:
  stage: deploy
  needs:
    - job: test:firmware
  script: 
    - lftp $OVH_URI -e "mirror --reverse --verbose -R ./.oi/bin/ ./www/oi-content/bin/; quit" -u $OVH_USERNAME,$OVH_PASSWORD
  rules:
    - if: '($CI_PIPELINE_SOURCE == "merge_request_event") && ($CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "master" || "dev")'

deploy:docs:
  stage: deploy
  needs:
    - job: build:docs
    - job: build:examples
  script:
    - lftp $OVH_URI -e "mirror --reverse --verbose --delete -R ./docs/build/html/ ./www/oi-content/doc/; quit" -u $OVH_USERNAME,$OVH_PASSWORD
  rules:
    - if: '($CI_PIPELINE_SOURCE == "merge_request_event") && ($CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "master" || "dev")'
